version: "2.3"

services:
  nansy_container:
    image: nansy:v0.0
    environment:
      - "LC_ALL=C.UTF-8"
      - "NVIDIA_VISIBLE_DEVICES=2,3"
    cpuset: "0-31,128-159"
    runtime: nvidia
    ipc: host
    ports:
      - "39964:39962"
      - "39965:8888"
    network_mode: bridge
    volumes:
      - "/home/dhchoi/NANSY:/root/NANSY"
      - "/raid/home/dhchoi:/raid/home/dhchoi"