class: datasets.css10.CSS10Dataset
load:
  audio: 'configs/audio/22k.yaml'

path:
  metadata: /raid/vision/dhchoi/data/CSS10/CSS_Finnish/transcript.txt
  root: /raid/vision/dhchoi/data/CSS10/CSS_Finnish
