class: VCTKDataset

path:
  root: /raid/audio/common/ttsdata/
  wav22: /raid/audio/common/ttsdata/VCTK-Corpus/wav22
  wav16: /raid/audio/common/ttsdata/VCTK-Corpus/wav16
  txt: /raid/audio/common/ttsdata/VCTK-Corpus/VCTK-Corpus/txt

  configs:
    train: /raid/audio/common/ttsdata/multi_filelist/vctk_22k_train.txt
    eval: /raid/audio/common/ttsdata/multi_filelist/vctk_22k_val.txt
    test: /raid/audio/common/ttsdata/multi_filelist/vctk_22k_test.txt
